/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMveW91c3MvT25lRHJpdmUvRGVza3RvcC9Bbmd1bGFyQ291cnMvQW5ndWxhclByb2plY3RzL2RlcGxveS1kZW1vL3NyYy9hcHAvbmF2YmFyL25hdmJhci5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL3lvdXNzL09uZURyaXZlL0Rlc2t0b3AvQW5ndWxhckNvdXJzL0FuZ3VsYXJQcm9qZWN0cy9kZXBsb3ktZGVtby9zcmMvYXBwL25hdmJhci9uYXZiYXIuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
